# Generated by Django 4.2.16 on 2024-10-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Categorie", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Post", "verbose_name_plural": "Posts"},
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="default-slug", max_length=200, unique=True),
        ),
    ]
