# Generated by Django 4.2.16 on 2024-10-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_category_options_alter_post_options_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="forum_link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
