# Generated by Django 4.2.16 on 2024-10-24 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_forum_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="date",
        ),
    ]
