# Generated by Django 4.2.17 on 2024-12-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contribution',
            field=models.BooleanField(default=False),
        ),
    ]
