# Generated by Django 4.2.17 on 2024-12-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_parent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
