# Generated by Django 4.2.17 on 2024-12-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_post_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_parent',
            field=models.IntegerField(default=0),
        ),
    ]
