# Generated by Django 4.2.17 on 2024-12-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_post_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.BooleanField(default=True),
        ),
    ]
