# Generated by Django 4.2.17 on 2024-12-26 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_posts', to='posts.post'),
        ),
    ]
