# Generated by Django 4.2.16 on 2024-10-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
