# Generated by Django 4.2.17 on 2024-12-23 16:48

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_avatar_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default.gif', upload_to=users.models.user_avatar_path),
        ),
    ]
