# Generated by Django 4.2.17 on 2025-01-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visitors', models.PositiveIntegerField(default=0)),
                ('last_reset', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
