# Generated by Django 4.2.17 on 2025-01-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='border_avatar',
            field=models.CharField(default='', max_length=50),
        ),
    ]
