# Generated by Django 4.2.17 on 2025-01-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_border_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username_decoration',
            field=models.CharField(default='', max_length=50),
        ),
    ]
