# Generated by Django 4.2.17 on 2025-01-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_username_decoration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='border_avatar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
