# Generated by Django 4.2.17 on 2025-01-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0002_remove_privatemessage_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessagesubject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
