# Generated by Django 4.2.16 on 2024-10-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guestbook",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("author", models.CharField(default="Visiteur", max_length=50)),
                ("content", models.CharField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
