# Generated by Django 4.2.16 on 2024-10-22 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_alter_category_options_topicread"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="forum.topic",
            ),
        ),
    ]
