# Generated by Django 4.2.17 on 2024-12-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Maintenance en cours', max_length=255, verbose_name='Titre de la maintenance')),
                ('content', models.TextField(verbose_name='Contenu de la maintenance')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
