# Generated by Django 4.2.17 on 2025-01-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='content',
            field=models.TextField(default='Votre site rétro favoris fait un chek-up ;)'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
