# Generated by Django 4.2.17 on 2024-12-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_littlebacgames_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='littlebacplayers',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
