# Generated by Django 4.2.17 on 2024-12-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_littlebacplayers_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='littlebacgames',
            name='players',
            field=models.ManyToManyField(related_name='little_bac_games', to='games.littlebacplayers'),
        ),
    ]
