# Generated by Django 4.2.17 on 2024-12-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_littlebacgames_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='littlebacgames',
            name='players',
        ),
    ]
