# Generated by Django 4.2.17 on 2024-12-30 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0006_remove_littlebacgames_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='littlebacgames',
            name='countdown_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='littlebacgames',
            name='countdown_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='littlebacanswers',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.littlebaccategories'),
        ),
        migrations.AlterField(
            model_name='littlebacanswers',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.littlebacplayers'),
        ),
        migrations.AlterField(
            model_name='littlebacanswers',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.littlebacrounds'),
        ),
        migrations.AlterField(
            model_name='littlebacgames',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='littlebacplayers',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.littlebacgames'),
        ),
        migrations.AlterField(
            model_name='littlebacplayers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='littlebacrounds',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='games.littlebacgames'),
        ),
    ]
