# Generated by Django 4.2.17 on 2024-12-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_littlebacgames_countdown_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='littlebacgames',
            name='countdown_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
