# Generated by Django 4.2.17 on 2024-12-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_littlebacgames_countdown_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='littlebacgames',
            name='countdown_start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
