# Generated by Django 4.2.17 on 2024-12-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_littlebacgames_countdown_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='littlebacplayers',
            name='status',
            field=models.CharField(choices=[('playing', 'Joue'), ('overed', 'A fini')], default='playing', max_length=20),
        ),
    ]
