# Generated by Django 4.2.17 on 2025-01-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_littlebacplayers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='littlebacgames',
            name='current_phase',
            field=models.CharField(blank=True, default='ready_game', max_length=60, null=True),
        ),
    ]
